get:
  description: Get product
  summary: Get product by id
  operationId: getProductById
  tags:
    - Product
  parameters:
    - name: productId
      required: true
      in: path
      description: product id
      schema:
        type: string
        format: uuid
  responses:
    '200':
      description: Get Product
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/v1/Product.yaml'
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/Problem.yaml'
    '404':
      description: Product Not Found